### ISSUE TITLE
Tmux Mac incompatibility option

### ISSUE THREAD

**Issue by dragonito** [DavidBadura/environment#14]
Hi,

> set-option -g status-utf8 on

this option is not available on Mac systems. Is it really used by linux systems?

Cu

Robin

**Comment by tolry** [comment]
This is not a mac specific problem, this also does not work with the tmux version from Ubuntu 16.10. You can skip the error message, but it's not very convenient.

I :+1: to remove the option and see how problematic this is with older tmux versions. I suspect, this doesn't matter, when you are not using non-ASCII chars for pane names.
