### ISSUE TITLE
change to zsh

### ISSUE THREAD

**Issue by DavidBadura** [DavidBadura/environment#8]

**Comment by tolry** [comment]
:-1:  :smile:

**Comment by DavidBadura** [comment]
Why? ;) 

I'm working on my lamp vagrant box and I have a lot of duplicated scripts. I want to reuse this repository.

**Comment by tolry** [comment]
:-1: because I use this in combination with bash, so, just selfish reasons :smile: But I can keep using my fork, so go ahead: if you've switched to zsh, this makes sense for you.

**Comment by tolry** [comment]
so you're not switching?

**Comment by DavidBadura** [comment]
No ;)
